# Generated by Django 5.1.4 on 2024-12-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMI_eXcent_App', '0003_diagnostic_question_display_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_question', models.CharField(default='1', max_length=10)),
                ('question_texte', models.TextField()),
                ('partie', models.CharField(default='Mise en Sécurité', max_length=100)),
                ('noms_photos', models.CharField(blank=True, max_length=255, null=True)),
                ('pictogrammes', models.CharField(blank=True, max_length=255, null=True)),
                ('id_question_suivante_oui', models.CharField(blank=True, max_length=10, null=True)),
                ('question_suivante_oui', models.TextField(blank=True, null=True)),
                ('partie_question_suivante_oui', models.CharField(blank=True, max_length=100, null=True)),
                ('id_question_suivante_non', models.CharField(blank=True, max_length=10, null=True)),
                ('question_suivante_non', models.TextField(blank=True, null=True)),
                ('partie_question_suivante_non', models.CharField(blank=True, max_length=100, null=True)),
                ('id_question_precedente', models.CharField(blank=True, max_length=10, null=True)),
                ('question_precedente', models.TextField(blank=True, null=True)),
                ('partie_question_precedente', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Question_display',
        ),
        migrations.AddConstraint(
            model_name='template_question',
            constraint=models.UniqueConstraint(fields=('id_question', 'partie'), name='unique_id_question_partie'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
