# Generated by Django 5.1.4 on 2024-12-31 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PMI_eXcent_App', '0005_alter_template_question_id_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template_question',
            name='id_question_precedente',
        ),
        migrations.RemoveField(
            model_name='template_question',
            name='partie_question_precedente',
        ),
        migrations.RemoveField(
            model_name='template_question',
            name='question_precedente',
        ),
    ]
