# Generated by Django 5.1.4 on 2025-01-03 07:35

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMI_eXcent_App', '0007_result_partie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template_question',
            name='question_suivante_non',
        ),
        migrations.RemoveField(
            model_name='template_question',
            name='question_suivante_oui',
        ),
        migrations.RemoveField(
            model_name='template_question',
            name='question_texte',
        ),
        migrations.AddField(
            model_name='template_question',
            name='id_question_suivante_3',
            field=models.CharField(blank=True, default='1', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='template_question',
            name='id_question_suivante_4',
            field=models.CharField(blank=True, default='1', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='template_question',
            name='id_question_suivante_5',
            field=models.CharField(blank=True, default='1', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='template_question',
            name='partie_question_suivante_3',
            field=models.CharField(blank=True, default='Mise en Sécurité', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='template_question',
            name='partie_question_suivante_4',
            field=models.CharField(blank=True, default='Mise en Sécurité', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='template_question',
            name='partie_question_suivante_5',
            field=models.CharField(blank=True, default='Mise en Sécurité', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='template_question',
            name='question_texte_EN',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='template_question',
            name='question_texte_FR',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='template_question',
            name='typeofquestion',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default=[], max_length=55, size=5),
        ),
    ]
