# Generated by Django 5.1.4 on 2025-01-03 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PMI_eXcent_App', '0008_remove_template_question_question_suivante_non_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='template_question',
            old_name='id_question_suivante_oui',
            new_name='id_question_suivante_1',
        ),
        migrations.RenameField(
            model_name='template_question',
            old_name='id_question_suivante_non',
            new_name='id_question_suivante_2',
        ),
        migrations.RenameField(
            model_name='template_question',
            old_name='partie_question_suivante_oui',
            new_name='partie_question_suivante_1',
        ),
        migrations.RenameField(
            model_name='template_question',
            old_name='partie_question_suivante_non',
            new_name='partie_question_suivante_2',
        ),
    ]
