# Generated by Django 5.1.4 on 2025-01-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMI_eXcent_App', '0012_alter_template_question_info_comp'),
    ]

    operations = [
        migrations.AddField(
            model_name='template_question',
            name='question_suivante_1_texte',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='template_question',
            name='question_suivante_2_texte',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
