# Generated by Django 5.1.4 on 2025-01-28 18:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMI_eXcent_App', '0013_template_question_question_suivante_1_texte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic_id', models.IntegerField()),
                ('partie', models.CharField(max_length=100)),
                ('id_question', models.CharField(max_length=10)),
                ('commentaire', models.TextField()),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameModel(
            old_name='Causes',
            new_name='Cause',
        ),
    ]
